# dummy_data.py - Steam API Key 없이 개발/테스트할 때 사용하는 더미 데이터

# ─────────────────────────────────────────
# 더미 유저 프로필
# ─────────────────────────────────────────
DUMMY_USERS = {
    "76561198000000001": {
        "steam_id": "76561198000000001",
        "username": "GameMaster_KR",
        "avatar_url": "https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg",
        "profile_url": "https://steamcommunity.com/id/gamemaster_kr",
    },
    "76561198000000002": {
        "steam_id": "76561198000000002",
        "username": "ProGamer_Seoul",
        "avatar_url": "https://avatars.steamstatic.com/b5bd56c1aa4644a474a2e4972be27ef9e82e517e_full.jpg",
        "profile_url": "https://steamcommunity.com/id/progamer_seoul",
    },
    "76561198000000003": {
        "steam_id": "76561198000000003",
        "username": "IndieHunter",
        "avatar_url": "https://avatars.steamstatic.com/4f6d65befd9ce5bf85f9336c620a02d3c55cfc0_full.jpg",
        "profile_url": "https://steamcommunity.com/id/indiehunter",
    },
}

# ─────────────────────────────────────────
# 게임 카탈로그 (app_id → 게임 정보)
# ─────────────────────────────────────────
GAME_CATALOG = {
    730: {
        "app_id": 730,
        "name": "Counter-Strike 2",
        "genres": ["Action", "FPS", "Shooter"],
        "tags": ["FPS", "Multiplayer", "Competitive", "Shooter", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
        "store_url": "https://store.steampowered.com/app/730",
        "metacritic": 83,
        "price": 0,
    },
    570: {
        "app_id": 570,
        "name": "Dota 2",
        "genres": ["Strategy", "MOBA", "Multiplayer"],
        "tags": ["MOBA", "Strategy", "Multiplayer", "Free to Play"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
        "store_url": "https://store.steampowered.com/app/570",
        "metacritic": 90,
        "price": 0,
    },
    1245620: {
        "app_id": 1245620,
        "name": "ELDEN RING",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "RPG", "Action", "Open World", "Dark Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
        "store_url": "https://store.steampowered.com/app/1245620",
        "metacritic": 95,
        "price": 59900,
    },
    1091500: {
        "app_id": 1091500,
        "name": "Cyberpunk 2077",
        "genres": ["RPG", "Action", "Open World"],
        "tags": ["Cyberpunk", "RPG", "Open World", "Action", "Sci-fi"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
        "store_url": "https://store.steampowered.com/app/1091500",
        "metacritic": 86,
        "price": 49900,
    },
    814380: {
        "app_id": 814380,
        "name": "Sekiro: Shadows Die Twice",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "Action", "RPG", "Difficult", "Samurai"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg",
        "store_url": "https://store.steampowered.com/app/814380",
        "metacritic": 91,
        "price": 39900,
    },
    1174180: {
        "app_id": 1174180,
        "name": "Red Dead Redemption 2",
        "genres": ["Adventure", "Action", "Open World"],
        "tags": ["Open World", "Story Rich", "Adventure", "Action", "Western"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg",
        "store_url": "https://store.steampowered.com/app/1174180",
        "metacritic": 93,
        "price": 59900,
    },
    292030: {
        "app_id": 292030,
        "name": "The Witcher 3: Wild Hunt",
        "genres": ["RPG", "Adventure", "Open World"],
        "tags": ["RPG", "Open World", "Story Rich", "Fantasy", "Adventure"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg",
        "store_url": "https://store.steampowered.com/app/292030",
        "metacritic": 92,
        "price": 29900,
    },
    881020: {
        "app_id": 881020,
        "name": "Hollow Knight",
        "genres": ["Indie", "Action", "Metroidvania"],
        "tags": ["Metroidvania", "Indie", "Difficult", "Atmospheric", "2D"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/881020/header.jpg",
        "store_url": "https://store.steampowered.com/app/881020",
        "metacritic": 87,
        "price": 14500,
    },
    413150: {
        "app_id": 413150,
        "name": "Stardew Valley",
        "genres": ["Indie", "RPG", "Simulation"],
        "tags": ["Farming Sim", "Indie", "RPG", "Relaxing", "Pixel Graphics"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg",
        "store_url": "https://store.steampowered.com/app/413150",
        "metacritic": 89,
        "price": 13500,
    },
    1237970: {
        "app_id": 1237970,
        "name": "Titanfall 2",
        "genres": ["Action", "FPS", "Shooter"],
        "tags": ["FPS", "Action", "Shooter", "Sci-fi", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1237970/header.jpg",
        "store_url": "https://store.steampowered.com/app/1237970",
        "metacritic": 89,
        "price": 19900,
    },
    1551360: {
        "app_id": 1551360,
        "name": "Forza Horizon 5",
        "genres": ["Racing", "Simulation", "Open World"],
        "tags": ["Racing", "Open World", "Driving", "Multiplayer", "Beautiful"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg",
        "store_url": "https://store.steampowered.com/app/1551360",
        "metacritic": 92,
        "price": 59900,
    },
    1085660: {
        "app_id": 1085660,
        "name": "Destiny 2",
        "genres": ["Action", "RPG", "Shooter"],
        "tags": ["Free to Play", "FPS", "RPG", "Co-op", "Sci-fi"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg",
        "store_url": "https://store.steampowered.com/app/1085660",
        "metacritic": 75,
        "price": 0,
    },
    1172470: {
        "app_id": 1172470,
        "name": "Apex Legends",
        "genres": ["Action", "FPS", "Battle Royale"],
        "tags": ["Battle Royale", "Free to Play", "FPS", "Multiplayer", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg",
        "store_url": "https://store.steampowered.com/app/1172470",
        "metacritic": 88,
        "price": 0,
    },
    524220: {
        "app_id": 524220,
        "name": "NieR: Automata",
        "genres": ["RPG", "Action", "Hack and Slash"],
        "tags": ["Action RPG", "Hack and Slash", "Story Rich", "Sci-fi", "Anime"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/524220/header.jpg",
        "store_url": "https://store.steampowered.com/app/524220",
        "metacritic": 88,
        "price": 35900,
    },
    990080: {
        "app_id": 990080,
        "name": "Hogwarts Legacy",
        "genres": ["RPG", "Adventure", "Open World"],
        "tags": ["Open World", "Magic", "RPG", "Adventure", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg",
        "store_url": "https://store.steampowered.com/app/990080",
        "metacritic": 84,
        "price": 59900,
    },
    1623730: {
        "app_id": 1623730,
        "name": "Palworld",
        "genres": ["Action", "Adventure", "Survival"],
        "tags": ["Survival", "Open World", "Crafting", "Multiplayer", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg",
        "store_url": "https://store.steampowered.com/app/1623730",
        "metacritic": 73,
        "price": 29900,
    },
    648800: {
        "app_id": 648800,
        "name": "Raft",
        "genres": ["Survival", "Adventure", "Indie"],
        "tags": ["Survival", "Crafting", "Multiplayer", "Open World", "Indie"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/648800/header.jpg",
        "store_url": "https://store.steampowered.com/app/648800",
        "metacritic": 0,
        "price": 19900,
    },
    578080: {
        "app_id": 578080,
        "name": "PUBG: BATTLEGROUNDS",
        "genres": ["Action", "Battle Royale", "Shooter"],
        "tags": ["Battle Royale", "Multiplayer", "Survival", "Shooter", "Third-Person"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg",
        "store_url": "https://store.steampowered.com/app/578080",
        "metacritic": 86,
        "price": 0,
    },
}

# ─────────────────────────────────────────
# 더미 유저별 소유 게임 + 플레이타임 (분 단위)
# ─────────────────────────────────────────
DUMMY_OWNED_GAMES = {
    "76561198000000001": [  # GameMaster_KR : FPS + Souls-like 유저
        {"app_id": 730,     "playtime_minutes": 12400, "name": "Counter-Strike 2"},
        {"app_id": 1172470, "playtime_minutes": 4300,  "name": "Apex Legends"},
        {"app_id": 1237970, "playtime_minutes": 2100,  "name": "Titanfall 2"},
        {"app_id": 1245620, "playtime_minutes": 3800,  "name": "ELDEN RING"},
        {"app_id": 814380,  "playtime_minutes": 2900,  "name": "Sekiro: Shadows Die Twice"},
        {"app_id": 292030,  "playtime_minutes": 1500,  "name": "The Witcher 3: Wild Hunt"},
        {"app_id": 1091500, "playtime_minutes": 900,   "name": "Cyberpunk 2077"},
    ],
    "76561198000000002": [  # ProGamer_Seoul : MOBA + FPS 유저
        {"app_id": 570,     "playtime_minutes": 28000, "name": "Dota 2"},
        {"app_id": 730,     "playtime_minutes": 8500,  "name": "Counter-Strike 2"},
        {"app_id": 1172470, "playtime_minutes": 5200,  "name": "Apex Legends"},
        {"app_id": 1085660, "playtime_minutes": 3100,  "name": "Destiny 2"},
        {"app_id": 1237970, "playtime_minutes": 1800,  "name": "Titanfall 2"},
    ],
    "76561198000000003": [  # IndieHunter : RPG + Indie 유저
        {"app_id": 413150,  "playtime_minutes": 9800,  "name": "Stardew Valley"},
        {"app_id": 881020,  "playtime_minutes": 6200,  "name": "Hollow Knight"},
        {"app_id": 292030,  "playtime_minutes": 5400,  "name": "The Witcher 3: Wild Hunt"},
        {"app_id": 524220,  "playtime_minutes": 4100,  "name": "NieR: Automata"},
        {"app_id": 1245620, "playtime_minutes": 2700,  "name": "ELDEN RING"},
        {"app_id": 990080,  "playtime_minutes": 1900,  "name": "Hogwarts Legacy"},
        {"app_id": 1174180, "playtime_minutes": 800,   "name": "Red Dead Redemption 2"},
    ],
}
