# dummy_data.py - Steam API Key 없이 개발/테스트할 때 사용하는 더미 데이터

# ─────────────────────────────────────────
# 더미 유저 프로필
# ─────────────────────────────────────────
DUMMY_USERS = {
    "76561198000000001": {
        "steam_id": "76561198000000001",
        "username": "GameMaster_KR",
        "avatar_url": "https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg",
        "profile_url": "https://steamcommunity.com/id/gamemaster_kr",
    },
    "76561198000000002": {
        "steam_id": "76561198000000002",
        "username": "ProGamer_Seoul",
        "avatar_url": "https://avatars.steamstatic.com/b5bd56c1aa4644a474a2e4972be27ef9e82e517e_full.jpg",
        "profile_url": "https://steamcommunity.com/id/progamer_seoul",
    },
    "76561198000000003": {
        "steam_id": "76561198000000003",
        "username": "IndieHunter",
        "avatar_url": "https://avatars.steamstatic.com/4f6d65befd9ce5bf85f9336c620a02d3c55cfc0_full.jpg",
        "profile_url": "https://steamcommunity.com/id/indiehunter",
    },
    "76561198000000004": {
        "steam_id": "76561198000000004",
        "username": "RPGAddict_KR",
        "avatar_url": "https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg",
        "profile_url": "https://steamcommunity.com/id/rpgaddict_kr",
    },
    "76561198000000005": {
        "steam_id": "76561198000000005",
        "username": "SurvivalKing",
        "avatar_url": "https://avatars.steamstatic.com/b5bd56c1aa4644a474a2e4972be27ef9e82e517e_full.jpg",
        "profile_url": "https://steamcommunity.com/id/survivalking",
    },
}

# ─────────────────────────────────────────
# 게임 카탈로그 (app_id → 게임 정보)
# ─────────────────────────────────────────
GAME_CATALOG = {
    # ── FPS / Shooter ────────────────────────
    730: {
        "name": "Counter-Strike 2",
        "genres": ["Action", "FPS", "Shooter"],
        "tags": ["FPS", "Multiplayer", "Competitive", "Shooter", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
        "store_url": "https://store.steampowered.com/app/730",
        "metacritic": 83, "price": 0,
    },
    1237970: {
        "name": "Titanfall 2",
        "genres": ["Action", "FPS", "Shooter"],
        "tags": ["FPS", "Action", "Shooter", "Sci-fi", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1237970/header.jpg",
        "store_url": "https://store.steampowered.com/app/1237970",
        "metacritic": 89, "price": 19900,
    },
    359550: {
        "name": "Tom Clancy's Rainbow Six Siege",
        "genres": ["Action", "FPS", "Tactical"],
        "tags": ["FPS", "Tactical", "Multiplayer", "Competitive", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/359550/header.jpg",
        "store_url": "https://store.steampowered.com/app/359550",
        "metacritic": 79, "price": 19900,
    },
    1938090: {
        "name": "Call of Duty: Modern Warfare III",
        "genres": ["Action", "FPS", "Shooter"],
        "tags": ["FPS", "Action", "Military", "Shooter", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1938090/header.jpg",
        "store_url": "https://store.steampowered.com/app/1938090",
        "metacritic": 57, "price": 79800,
    },
    2519060: {
        "name": "Helldivers 2",
        "genres": ["Action", "Shooter", "Co-op"],
        "tags": ["Co-op", "Third-Person Shooter", "Action", "Sci-fi", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2519060/header.jpg",
        "store_url": "https://store.steampowered.com/app/2519060",
        "metacritic": 82, "price": 39900,
    },
    # ── Battle Royale ─────────────────────────
    1172470: {
        "name": "Apex Legends",
        "genres": ["Action", "FPS", "Battle Royale"],
        "tags": ["Battle Royale", "Free to Play", "FPS", "Multiplayer", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg",
        "store_url": "https://store.steampowered.com/app/1172470",
        "metacritic": 88, "price": 0,
    },
    578080: {
        "name": "PUBG: BATTLEGROUNDS",
        "genres": ["Action", "Battle Royale", "Shooter"],
        "tags": ["Battle Royale", "Multiplayer", "Survival", "Shooter", "Third-Person"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg",
        "store_url": "https://store.steampowered.com/app/578080",
        "metacritic": 86, "price": 0,
    },
    # ── RPG / Action-RPG ──────────────────────
    1245620: {
        "name": "ELDEN RING",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "RPG", "Action", "Open World", "Dark Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
        "store_url": "https://store.steampowered.com/app/1245620",
        "metacritic": 95, "price": 59900,
    },
    1091500: {
        "name": "Cyberpunk 2077",
        "genres": ["RPG", "Action", "Open World"],
        "tags": ["Cyberpunk", "RPG", "Open World", "Action", "Sci-fi"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
        "store_url": "https://store.steampowered.com/app/1091500",
        "metacritic": 86, "price": 49900,
    },
    814380: {
        "name": "Sekiro: Shadows Die Twice",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "Action", "RPG", "Difficult", "Samurai"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg",
        "store_url": "https://store.steampowered.com/app/814380",
        "metacritic": 91, "price": 39900,
    },
    292030: {
        "name": "The Witcher 3: Wild Hunt",
        "genres": ["RPG", "Adventure", "Open World"],
        "tags": ["RPG", "Open World", "Story Rich", "Fantasy", "Adventure"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg",
        "store_url": "https://store.steampowered.com/app/292030",
        "metacritic": 92, "price": 29900,
    },
    524220: {
        "name": "NieR: Automata",
        "genres": ["RPG", "Action", "Hack and Slash"],
        "tags": ["Action RPG", "Hack and Slash", "Story Rich", "Sci-fi", "Anime"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/524220/header.jpg",
        "store_url": "https://store.steampowered.com/app/524220",
        "metacritic": 88, "price": 35900,
    },
    990080: {
        "name": "Hogwarts Legacy",
        "genres": ["RPG", "Adventure", "Open World"],
        "tags": ["Open World", "Magic", "RPG", "Adventure", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg",
        "store_url": "https://store.steampowered.com/app/990080",
        "metacritic": 84, "price": 59900,
    },
    1174180: {
        "name": "Red Dead Redemption 2",
        "genres": ["Adventure", "Action", "Open World"],
        "tags": ["Open World", "Story Rich", "Adventure", "Action", "Western"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg",
        "store_url": "https://store.steampowered.com/app/1174180",
        "metacritic": 93, "price": 59900,
    },
    2215430: {
        "name": "Baldur's Gate 3",
        "genres": ["RPG", "Adventure", "Strategy"],
        "tags": ["RPG", "Story Rich", "Co-op", "Turn-Based", "Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2215430/header.jpg",
        "store_url": "https://store.steampowered.com/app/2215430",
        "metacritic": 96, "price": 59900,
    },
    1086940: {
        "name": "Baldur's Gate 3 (Early Access)",
        "genres": ["RPG", "Adventure", "Strategy"],
        "tags": ["RPG", "Story Rich", "Co-op", "Turn-Based", "Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg",
        "store_url": "https://store.steampowered.com/app/1086940",
        "metacritic": 96, "price": 59900,
    },
    1172620: {
        "name": "Dark Souls III",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "Action", "RPG", "Difficult", "Dark Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/374320/header.jpg",
        "store_url": "https://store.steampowered.com/app/374320",
        "metacritic": 89, "price": 39900,
    },
    374320: {
        "name": "Dark Souls III",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Souls-like", "Action", "RPG", "Difficult", "Dark Fantasy"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/374320/header.jpg",
        "store_url": "https://store.steampowered.com/app/374320",
        "metacritic": 89, "price": 39900,
    },
    # ── Adventure / Open World ────────────────
    1085660: {
        "name": "Destiny 2",
        "genres": ["Action", "RPG", "Shooter"],
        "tags": ["Free to Play", "FPS", "RPG", "Co-op", "Sci-fi"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg",
        "store_url": "https://store.steampowered.com/app/1085660",
        "metacritic": 75, "price": 0,
    },
    1623730: {
        "name": "Palworld",
        "genres": ["Action", "Adventure", "Survival"],
        "tags": ["Survival", "Open World", "Crafting", "Multiplayer", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg",
        "store_url": "https://store.steampowered.com/app/1623730",
        "metacritic": 73, "price": 29900,
    },
    1888930: {
        "name": "The Last of Us Part I",
        "genres": ["Adventure", "Action", "Story Rich"],
        "tags": ["Story Rich", "Action", "Post-Apocalyptic", "Survival", "Third-Person"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1888930/header.jpg",
        "store_url": "https://store.steampowered.com/app/1888930",
        "metacritic": 88, "price": 59900,
    },
    2358720: {
        "name": "Black Myth: Wukong",
        "genres": ["RPG", "Action", "Souls-like"],
        "tags": ["Action RPG", "Souls-like", "Mythology", "Difficult", "Story Rich"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2358720/header.jpg",
        "store_url": "https://store.steampowered.com/app/2358720",
        "metacritic": 82, "price": 59900,
    },
    # ── Indie ────────────────────────────────
    881020: {
        "name": "Hollow Knight",
        "genres": ["Indie", "Action", "Metroidvania"],
        "tags": ["Metroidvania", "Indie", "Difficult", "Atmospheric", "2D"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/881020/header.jpg",
        "store_url": "https://store.steampowered.com/app/881020",
        "metacritic": 87, "price": 14500,
    },
    413150: {
        "name": "Stardew Valley",
        "genres": ["Indie", "RPG", "Simulation"],
        "tags": ["Farming Sim", "Indie", "RPG", "Relaxing", "Pixel Graphics"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg",
        "store_url": "https://store.steampowered.com/app/413150",
        "metacritic": 89, "price": 13500,
    },
    1145360: {
        "name": "Hades",
        "genres": ["Indie", "Action", "Roguelike"],
        "tags": ["Roguelike", "Action", "Indie", "Mythology", "Hack and Slash"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg",
        "store_url": "https://store.steampowered.com/app/1145360",
        "metacritic": 93, "price": 24500,
    },
    1794680: {
        "name": "Vampire Survivors",
        "genres": ["Indie", "Action", "Roguelike"],
        "tags": ["Roguelike", "Indie", "Action", "Bullet Hell", "Survival"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1794680/header.jpg",
        "store_url": "https://store.steampowered.com/app/1794680",
        "metacritic": 86, "price": 4500,
    },
    367520: {
        "name": "Hollow Knight (Demo)",
        "genres": ["Indie", "Action", "Metroidvania"],
        "tags": ["Metroidvania", "Indie", "Atmospheric", "2D", "Difficult"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/881020/header.jpg",
        "store_url": "https://store.steampowered.com/app/881020",
        "metacritic": 87, "price": 0,
    },
    1649520: {
        "name": "Inscryption",
        "genres": ["Indie", "Strategy", "Roguelike"],
        "tags": ["Roguelike", "Card Game", "Indie", "Horror", "Mystery"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1649520/header.jpg",
        "store_url": "https://store.steampowered.com/app/1649520",
        "metacritic": 85, "price": 16500,
    },
    # ── Strategy ─────────────────────────────
    570: {
        "name": "Dota 2",
        "genres": ["Strategy", "MOBA", "Multiplayer"],
        "tags": ["MOBA", "Strategy", "Multiplayer", "Free to Play"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
        "store_url": "https://store.steampowered.com/app/570",
        "metacritic": 90, "price": 0,
    },
    289070: {
        "name": "Sid Meier's Civilization VI",
        "genres": ["Strategy", "Simulation", "Turn-Based"],
        "tags": ["Turn-Based Strategy", "Strategy", "Historical", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/289070/header.jpg",
        "store_url": "https://store.steampowered.com/app/289070",
        "metacritic": 88, "price": 59900,
    },
    8930: {
        "name": "Sid Meier's Civilization V",
        "genres": ["Strategy", "Simulation", "Turn-Based"],
        "tags": ["Turn-Based Strategy", "Strategy", "Historical", "Multiplayer"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/8930/header.jpg",
        "store_url": "https://store.steampowered.com/app/8930",
        "metacritic": 90, "price": 29900,
    },
    1158310: {
        "name": "Crusader Kings III",
        "genres": ["Strategy", "RPG", "Simulation"],
        "tags": ["Grand Strategy", "Medieval", "RPG", "Sandbox", "Historical"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1158310/header.jpg",
        "store_url": "https://store.steampowered.com/app/1158310",
        "metacritic": 91, "price": 49900,
    },
    # ── Survival / Sandbox ────────────────────
    648800: {
        "name": "Raft",
        "genres": ["Survival", "Adventure", "Indie"],
        "tags": ["Survival", "Crafting", "Multiplayer", "Open World", "Indie"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/648800/header.jpg",
        "store_url": "https://store.steampowered.com/app/648800",
        "metacritic": 0, "price": 19900,
    },
    252490: {
        "name": "Rust",
        "genres": ["Survival", "Action", "Multiplayer"],
        "tags": ["Survival", "Multiplayer", "Crafting", "Open World", "PvP"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg",
        "store_url": "https://store.steampowered.com/app/252490",
        "metacritic": 69, "price": 39900,
    },
    108600: {
        "name": "Project Zomboid",
        "genres": ["Survival", "Indie", "RPG"],
        "tags": ["Survival", "Zombie", "Open World", "Sandbox", "Co-op"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/108600/header.jpg",
        "store_url": "https://store.steampowered.com/app/108600",
        "metacritic": 0, "price": 19900,
    },
    1167630: {
        "name": "Valheim",
        "genres": ["Survival", "Adventure", "Indie"],
        "tags": ["Survival", "Viking", "Open World", "Co-op", "Crafting"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1167630/header.jpg",
        "store_url": "https://store.steampowered.com/app/1167630",
        "metacritic": 80, "price": 19900,
    },
    # ── Racing / Sports ───────────────────────
    1551360: {
        "name": "Forza Horizon 5",
        "genres": ["Racing", "Simulation", "Open World"],
        "tags": ["Racing", "Open World", "Driving", "Multiplayer", "Beautiful"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg",
        "store_url": "https://store.steampowered.com/app/1551360",
        "metacritic": 92, "price": 59900,
    },
    1240440: {
        "name": "Halo Infinite",
        "genres": ["Action", "FPS", "Sci-fi"],
        "tags": ["FPS", "Sci-fi", "Multiplayer", "Action", "Story Rich"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1240440/header.jpg",
        "store_url": "https://store.steampowered.com/app/1240440",
        "metacritic": 87, "price": 0,
    },
    # ── Horror / Thriller ─────────────────────
    976730: {
        "name": "Hades (Beta)",
        "genres": ["Indie", "Action", "Roguelike"],
        "tags": ["Roguelike", "Action", "Indie"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg",
        "store_url": "https://store.steampowered.com/app/1145360",
        "metacritic": 93, "price": 0,
    },
    418370: {
        "name": "Resident Evil 7: Biohazard",
        "genres": ["Action", "Horror", "Adventure"],
        "tags": ["Horror", "First-Person", "Survival Horror", "Story Rich", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/418370/header.jpg",
        "store_url": "https://store.steampowered.com/app/418370",
        "metacritic": 86, "price": 29900,
    },
    952060: {
        "name": "Resident Evil Village",
        "genres": ["Action", "Horror", "Adventure"],
        "tags": ["Horror", "First-Person", "Survival Horror", "Story Rich", "Action"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/952060/header.jpg",
        "store_url": "https://store.steampowered.com/app/952060",
        "metacritic": 84, "price": 39900,
    },
    # ── Simulation ────────────────────────────
    1284210: {
        "name": "Microsoft Flight Simulator",
        "genres": ["Simulation", "Flying"],
        "tags": ["Flight", "Simulation", "Realistic", "Open World", "Beautiful"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1284210/header.jpg",
        "store_url": "https://store.steampowered.com/app/1284210",
        "metacritic": 91, "price": 79900,
    },
    # ── Platformer ────────────────────────────
    1113560: {
        "name": "Celeste",
        "genres": ["Indie", "Platformer", "Action"],
        "tags": ["Platformer", "Indie", "Difficult", "Story Rich", "Pixel Graphics"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg",
        "store_url": "https://store.steampowered.com/app/504230",
        "metacritic": 94, "price": 19900,
    },
    504230: {
        "name": "Celeste",
        "genres": ["Indie", "Platformer", "Action"],
        "tags": ["Platformer", "Indie", "Difficult", "Story Rich", "Pixel Graphics"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg",
        "store_url": "https://store.steampowered.com/app/504230",
        "metacritic": 94, "price": 19900,
    },
    # ── MMO / Online ──────────────────────────
    230410: {
        "name": "Warframe",
        "genres": ["Action", "RPG", "Shooter"],
        "tags": ["Free to Play", "Third-Person Shooter", "Action RPG", "Co-op", "Sci-fi"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg",
        "store_url": "https://store.steampowered.com/app/230410",
        "metacritic": 0, "price": 0,
    },
    2933620: {
        "name": "Path of Exile 2",
        "genres": ["RPG", "Action", "Hack and Slash"],
        "tags": ["Action RPG", "Hack and Slash", "Dark Fantasy", "Isometric", "Free to Play"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2933620/header.jpg",
        "store_url": "https://store.steampowered.com/app/2933620",
        "metacritic": 0, "price": 0,
    },
    1599340: {
        "name": "Lost Ark",
        "genres": ["RPG", "Action", "MMORPG"],
        "tags": ["MMORPG", "Free to Play", "Action RPG", "Isometric", "Co-op"],
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1599340/header.jpg",
        "store_url": "https://store.steampowered.com/app/1599340",
        "metacritic": 76, "price": 0,
    },
}

# ─────────────────────────────────────────
# 더미 유저별 소유 게임 + 플레이타임 (분 단위)
# ─────────────────────────────────────────
DUMMY_OWNED_GAMES = {
    "76561198000000001": [  # GameMaster_KR : FPS + Souls-like
        {"app_id": 730,     "playtime_minutes": 12400, "name": "Counter-Strike 2"},
        {"app_id": 1172470, "playtime_minutes": 4300,  "name": "Apex Legends"},
        {"app_id": 1237970, "playtime_minutes": 2100,  "name": "Titanfall 2"},
        {"app_id": 1245620, "playtime_minutes": 3800,  "name": "ELDEN RING"},
        {"app_id": 814380,  "playtime_minutes": 2900,  "name": "Sekiro: Shadows Die Twice"},
        {"app_id": 292030,  "playtime_minutes": 1500,  "name": "The Witcher 3: Wild Hunt"},
        {"app_id": 1091500, "playtime_minutes": 900,   "name": "Cyberpunk 2077"},
        {"app_id": 359550,  "playtime_minutes": 3200,  "name": "Rainbow Six Siege"},
        {"app_id": 2358720, "playtime_minutes": 1800,  "name": "Black Myth: Wukong"},
        {"app_id": 374320,  "playtime_minutes": 2200,  "name": "Dark Souls III"},
    ],
    "76561198000000002": [  # ProGamer_Seoul : MOBA + FPS
        {"app_id": 570,     "playtime_minutes": 28000, "name": "Dota 2"},
        {"app_id": 730,     "playtime_minutes": 8500,  "name": "Counter-Strike 2"},
        {"app_id": 1172470, "playtime_minutes": 5200,  "name": "Apex Legends"},
        {"app_id": 1085660, "playtime_minutes": 3100,  "name": "Destiny 2"},
        {"app_id": 1237970, "playtime_minutes": 1800,  "name": "Titanfall 2"},
        {"app_id": 578080,  "playtime_minutes": 4100,  "name": "PUBG"},
        {"app_id": 1240440, "playtime_minutes": 2200,  "name": "Halo Infinite"},
        {"app_id": 2519060, "playtime_minutes": 1500,  "name": "Helldivers 2"},
    ],
    "76561198000000003": [  # IndieHunter : RPG + Indie
        {"app_id": 413150,  "playtime_minutes": 9800,  "name": "Stardew Valley"},
        {"app_id": 881020,  "playtime_minutes": 6200,  "name": "Hollow Knight"},
        {"app_id": 292030,  "playtime_minutes": 5400,  "name": "The Witcher 3: Wild Hunt"},
        {"app_id": 524220,  "playtime_minutes": 4100,  "name": "NieR: Automata"},
        {"app_id": 1245620, "playtime_minutes": 2700,  "name": "ELDEN RING"},
        {"app_id": 990080,  "playtime_minutes": 1900,  "name": "Hogwarts Legacy"},
        {"app_id": 1174180, "playtime_minutes": 800,   "name": "Red Dead Redemption 2"},
        {"app_id": 1145360, "playtime_minutes": 3500,  "name": "Hades"},
        {"app_id": 1794680, "playtime_minutes": 2800,  "name": "Vampire Survivors"},
        {"app_id": 1649520, "playtime_minutes": 1600,  "name": "Inscryption"},
        {"app_id": 504230,  "playtime_minutes": 2100,  "name": "Celeste"},
    ],
    "76561198000000004": [  # RPGAddict_KR : 대형 RPG 위주
        {"app_id": 2215430, "playtime_minutes": 14000, "name": "Baldur's Gate 3"},
        {"app_id": 292030,  "playtime_minutes": 8000,  "name": "The Witcher 3: Wild Hunt"},
        {"app_id": 1091500, "playtime_minutes": 6500,  "name": "Cyberpunk 2077"},
        {"app_id": 1245620, "playtime_minutes": 5200,  "name": "ELDEN RING"},
        {"app_id": 1158310, "playtime_minutes": 7800,  "name": "Crusader Kings III"},
        {"app_id": 990080,  "playtime_minutes": 3200,  "name": "Hogwarts Legacy"},
        {"app_id": 1174180, "playtime_minutes": 4100,  "name": "Red Dead Redemption 2"},
        {"app_id": 524220,  "playtime_minutes": 3500,  "name": "NieR: Automata"},
        {"app_id": 1888930, "playtime_minutes": 2200,  "name": "The Last of Us Part I"},
    ],
    "76561198000000005": [  # SurvivalKing : Survival + Sandbox
        {"app_id": 252490,  "playtime_minutes": 15000, "name": "Rust"},
        {"app_id": 1167630, "playtime_minutes": 6800,  "name": "Valheim"},
        {"app_id": 648800,  "playtime_minutes": 4200,  "name": "Raft"},
        {"app_id": 108600,  "playtime_minutes": 5500,  "name": "Project Zomboid"},
        {"app_id": 1623730, "playtime_minutes": 3800,  "name": "Palworld"},
        {"app_id": 578080,  "playtime_minutes": 2900,  "name": "PUBG"},
        {"app_id": 1172470, "playtime_minutes": 1800,  "name": "Apex Legends"},
        {"app_id": 2519060, "playtime_minutes": 2200,  "name": "Helldivers 2"},
    ],
}
